---

- name: Start etcd container
  docker:
    name: "etcd-{{ ansible_hostname }}"
    image: "quay.io/coreos/etcd:v{{ ETCDVERSION }}"
    state: reloaded
    ports:
    - "4001:4001"
    - "2380:2380"
    - "2379:2379"
    volumes:
    - "{{ CERT_DIR }}:{{ CERT_DIR }}"
    env:
      ETCD_CERT_FILE: "{{ CERT_DIR }}/server-cert.pem"
      ETCD_KEY_FILE: "{{ CERT_DIR }}/server-key.pem"
      ETCD_TRUSTED_CA_FILE: "{{ CERT_DIR }}/ca-cert.pem"
      ETCD_CLIENT_CERT_AUTH: true
      ETCD_PEER_CERT_FILE: "{{ CERT_DIR }}/server-cert.pem"
      ETCD_PEER_KEY_FILE: "{{ CERT_DIR }}/server-key.pem"
      ETCD_PEER_TRUSTED_CA_FILE: "{{ CERT_DIR }}/ca-cert.pem"
      ETCD_PEER_CLIENT_CERT_AUTH: true
    command: >
             -name etcd-{{ ansible_hostname }}.yooser.org 
             -advertise-client-urls https://{{ ansible_eth0.ipv4.address }}:2379,https://{{ ansible_eth0.ipv4.address }}:4001 
             -listen-client-urls https://0.0.0.0:2379,https://0.0.0.0:4001 
             -initial-advertise-peer-urls https://{{ ansible_eth0.ipv4.address }}:2380 
             -listen-peer-urls https://0.0.0.0:2380 
             -initial-cluster-token etcd-cluster-1 
             -initial-cluster {{ etcd_cluster_string }}
             -initial-cluster-state new
